version: '3'
services:
  frontend:
    build: ./frontend
    container_name: khongfamily_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080

    depends_on:
      - backend
      # - reverse-proxy
  backend:
    build: ./backend
    container_name: khongfamily_backend
    ports:
      - "8080:8080"
    # volumes:
    #   - ./backend:/app
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=khongadmin
      - DB_PASSWORD=khong1314Family
      - DB_NAME=khongfamily
    depends_on:
      - database
  database:
    image: postgres
    container_name: khongfamily_database
    environment:
      - POSTGRES_USER=khongadmin
      - POSTGRES_PASSWORD=khong1314Family
      - POSTGRES_DB=khongfamily
    volumes:
      - ./sqlscript/initUser.sql:/docker-entrypoint-initdb.d/initUser.sql
      - ./sqlscript/initTables.sql:/docker-entrypoint-initdb.d/initTables.sql
      - ./database:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
