// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID                int32
	ExpenseCategoryID int32
	AmountCents       int32
	Description       string
	Date              pgtype.Date
	Remarks           string
}

type ExpenseCategory struct {
	ID          int32
	Name        string
	Description string
}

type User struct {
	ID        int32
	Name      string
	Email     string
	Password  string
	Role      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
