import "../styles/main.css";
import { poppins } from "@/utils/fonts";
import Header from "@/components/Header";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>

      <body className={`${poppins.variable} font-poppins`}>
        <Header />
        {children}
      </body>
      </AuthProvider>
    </html>
  )
}
